export const cities = [
  {
    slug: "seattle",
    city: "Seattle",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Seattle, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Seattle — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Seattle residents rely on Noble Medic Wheels for safe, on-time non-emergency cabulance and medical transportation. Whether you need a wheelchair-accessible ride to a specialist, recurring dialysis transport, or a same-day hospital discharge ride, our professional drivers serve all Seattle neighborhoods with dignity and care.",
    highlights: ["UW Medical Center & Harborview area", "Dialysis centers throughout the city", "All Seattle zip codes covered", "Door-to-door service"],
    nearbyAreas: ["Renton", "Burien", "Tukwila", "SeaTac"],
  },
  {
    slug: "tacoma",
    city: "Tacoma",
    county: "Pierce County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Tacoma, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Tacoma — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Tacoma patients and families trust Noble Medic Wheels for dependable, door-to-door non-emergency cabulance and medical transportation across Pierce County. We serve all Tacoma zip codes with ADA-compliant vehicles and professionally trained drivers who treat every rider with dignity.",
    highlights: ["MultiCare Tacoma General & St. Joseph Medical Center", "Recurring dialysis scheduling", "All Pierce County zip codes", "Wheelchair & ambulatory service"],
    nearbyAreas: ["Lakewood", "Puyallup", "Fife", "University Place"],
  },
  {
    slug: "everett",
    city: "Everett",
    county: "Snohomish County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Everett, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Everett — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "As Snohomish County's largest city, Everett patients rely on Noble Medic Wheels for professional non-emergency cabulance and medical transportation. From Providence Regional Medical Center to local dialysis centers, we get you there safely and on time, every time.",
    highlights: ["Providence Regional Medical Center", "Snohomish County dialysis centers", "Wheelchair lift-equipped vans", "Same-day & scheduled rides"],
    nearbyAreas: ["Marysville", "Mukilteo", "Mill Creek", "Lynnwood"],
  },
  {
    slug: "renton",
    city: "Renton",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Renton, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Renton — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Renton residents have trusted Noble Medic Wheels for reliable, compassionate non-emergency cabulance and medical transportation. From Valley Medical Center to local dialysis clinics, we handle every trip with care and punctuality so you never miss an appointment.",
    highlights: ["Valley Medical Center & nearby clinics", "Recurring dialysis transport", "King County coverage", "ADA-compliant fleet"],
    nearbyAreas: ["Kent", "Tukwila", "Burien", "Newcastle"],
  },
  {
    slug: "lynnwood",
    city: "Lynnwood",
    county: "Snohomish County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Lynnwood, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Lynnwood — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Noble Medic Wheels provides Lynnwood residents with safe, ADA-compliant non-emergency cabulance and medical transportation throughout Snohomish County. Whether heading to Swedish Edmonds, a dialysis center, or a specialist appointment, our drivers are always prompt and professional.",
    highlights: ["Swedish Edmonds & local clinics", "Snohomish County dialysis centers", "Flexible scheduling", "Wheelchair & ambulatory rides"],
    nearbyAreas: ["Edmonds", "Mountlake Terrace", "Bothell", "Everett"],
  },
  {
    slug: "federal-way",
    city: "Federal Way",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Federal Way, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Federal Way — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Federal Way patients and families count on Noble Medic Wheels for dependable, dignified non-emergency cabulance and medical transportation. We serve St. Francis Hospital, dialysis centers, and all medical facilities throughout Federal Way with on-time, door-to-door service.",
    highlights: ["St. Francis Hospital area", "Dialysis & recurring appointments", "All Federal Way zip codes", "Door-to-door assistance"],
    nearbyAreas: ["Auburn", "Kent", "Des Moines", "Tacoma"],
  },
  {
    slug: "marysville",
    city: "Marysville",
    county: "Snohomish County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Marysville, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Marysville — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Marysville residents in Snohomish County rely on Noble Medic Wheels for professional non-emergency cabulance and medical transportation. We serve Smokey Point Medical Center, local dialysis clinics, and all medical facilities in and around Marysville with care and reliability.",
    highlights: ["Smokey Point Medical Center", "Snohomish County routes", "Scheduled & recurring rides", "Wheelchair-accessible vehicles"],
    nearbyAreas: ["Everett", "Arlington", "Stanwood", "Lake Stevens"],
  },
  {
    slug: "lakewood",
    city: "Lakewood",
    county: "Pierce County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Lakewood, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Lakewood — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Lakewood patients trust Noble Medic Wheels for safe, reliable non-emergency cabulance and medical transportation in Pierce County. From local dialysis centers to specialist appointments and hospital discharges, we provide compassionate, on-time service throughout Lakewood.",
    highlights: ["Pierce County dialysis centers", "Hospital discharge coordination", "ADA-compliant vehicles", "Wheelchair & ambulatory service"],
    nearbyAreas: ["Tacoma", "University Place", "Puyallup", "Spanaway"],
  },
  {
    slug: "kent",
    city: "Kent",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Kent, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Kent — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Kent residents rely on Noble Medic Wheels for safe, on-time non-emergency cabulance and medical transportation across King County. Whether it's a recurring dialysis schedule, a specialist appointment, or a hospital discharge, our drivers provide door-to-door service with dignity and care.",
    highlights: ["Recurring dialysis scheduling", "King County coverage", "ADA-compliant, wheelchair-accessible vans", "Door-to-door assistance"],
    nearbyAreas: ["Renton", "Auburn", "Federal Way", "Covington"],
  },
  {
    slug: "burien",
    city: "Burien",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Burien, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Burien — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Burien residents count on Noble Medic Wheels for dependable, ADA-compliant non-emergency cabulance and medical transportation. Our drivers know the Highline medical community well and provide punctual, door-to-door rides to dialysis, specialist visits, and hospital discharges.",
    highlights: ["Highline medical community", "Recurring dialysis transport", "Wheelchair-accessible vans", "King County coverage"],
    nearbyAreas: ["Seattle", "Tukwila", "SeaTac", "Des Moines"],
  },
  {
    slug: "tukwila",
    city: "Tukwila",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Tukwila, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Tukwila — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Tukwila patients and families trust Noble Medic Wheels for safe, reliable non-emergency cabulance and medical transportation. From dialysis appointments to hospital discharges, our ADA-compliant vans and trained drivers serve Tukwila with punctuality and care.",
    highlights: ["Central King County location", "Recurring dialysis scheduling", "Wheelchair-accessible vans", "Door-to-door service"],
    nearbyAreas: ["Seattle", "Renton", "Burien", "SeaTac"],
  },
  {
    slug: "seatac",
    city: "SeaTac",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in SeaTac, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in SeaTac — wheelchair rides, dialysis transport, and airport transportation. Call 253-374-9087.",
    intro: "SeaTac residents and travelers rely on Noble Medic Wheels for wheelchair-accessible, non-emergency cabulance and medical transportation, including trips to and from Seattle-Tacoma International Airport for medical-related travel. Our drivers provide door-to-door assistance for every ride.",
    highlights: ["Wheelchair-accessible airport transportation", "Recurring dialysis transport", "ADA-compliant vans", "King County coverage"],
    nearbyAreas: ["Burien", "Tukwila", "Des Moines", "Federal Way"],
  },
  {
    slug: "puyallup",
    city: "Puyallup",
    county: "Pierce County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Puyallup, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Puyallup — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Puyallup patients rely on Noble Medic Wheels for dependable, ADA-compliant non-emergency cabulance and medical transportation across Pierce County. From MultiCare Good Samaritan Hospital to local dialysis centers, our drivers provide safe, on-time, door-to-door rides.",
    highlights: ["MultiCare Good Samaritan Hospital area", "Recurring dialysis scheduling", "Wheelchair-accessible vans", "Pierce County coverage"],
    nearbyAreas: ["Tacoma", "Lakewood", "Sumner", "Fife"],
  },
  {
    slug: "auburn",
    city: "Auburn",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Auburn, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Auburn — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Auburn residents trust Noble Medic Wheels for safe, reliable non-emergency cabulance and medical transportation. From MultiCare Auburn Medical Center to dialysis centers and specialist appointments, our ADA-compliant vans and trained drivers get you there on time.",
    highlights: ["MultiCare Auburn Medical Center area", "Recurring dialysis transport", "Wheelchair-accessible vans", "King & Pierce County coverage"],
    nearbyAreas: ["Kent", "Federal Way", "Puyallup", "Des Moines"],
  },
  {
    slug: "edmonds",
    city: "Edmonds",
    county: "Snohomish County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Edmonds, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Edmonds — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Edmonds residents rely on Noble Medic Wheels for dependable, ADA-compliant non-emergency cabulance and medical transportation. From Swedish Edmonds to local dialysis centers, our professional drivers provide punctual, door-to-door service throughout Snohomish County.",
    highlights: ["Swedish Edmonds area", "Recurring dialysis scheduling", "Wheelchair-accessible vans", "Snohomish County coverage"],
    nearbyAreas: ["Lynnwood", "Mountlake Terrace", "Mukilteo", "Everett"],
  },
  {
    slug: "des-moines",
    city: "Des Moines",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Cabulance & NEMT in Des Moines, WA",
    metaDesc: "Noble Medic Wheels offers non-emergency cabulance and NEMT in Des Moines, WA — wheelchair rides, dialysis transport, hospital discharges. Call 253-374-9087.",
    intro: "Des Moines residents count on Noble Medic Wheels for safe, reliable non-emergency cabulance and medical transportation across King County. Our ADA-compliant vans and trained drivers provide door-to-door assistance for dialysis, specialist visits, and hospital discharges.",
    highlights: ["Recurring dialysis transport", "Wheelchair-accessible vans", "King County coverage", "Door-to-door assistance"],
    nearbyAreas: ["Burien", "SeaTac", "Federal Way", "Kent"],
  },
];
