export const cities = [
  {
    slug: "seattle",
    city: "Seattle",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Medical Transportation in Seattle, WA",
    metaDesc: "Noble Medic Wheels provides ADA-compliant non-emergency ambulance and NEMT in Seattle — wheelchair rides, dialysis transport, and hospital discharges. Serving all Seattle neighborhoods. Call 253-374-9087.",
    intro: "Seattle residents rely on Noble Medic Wheels for safe, on-time non-emergency ambulance and medical transportation. Whether you need a wheelchair-accessible ride to a specialist, recurring dialysis transport, or a same-day hospital discharge ride, our professional drivers serve all Seattle neighborhoods with dignity and care.",
    highlights: ["UW Medical Center & Harborview area", "Dialysis centers throughout the city", "All Seattle zip codes covered", "Door-to-door service"],
    nearbyAreas: ["Renton", "Burien", "Tukwila", "SeaTac"],
  },
  {
    slug: "tacoma",
    city: "Tacoma",
    county: "Pierce County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Wheelchair Transportation in Tacoma, WA",
    metaDesc: "Noble Medic Wheels offers reliable non-emergency ambulance and medical transportation in Tacoma — ADA-compliant wheelchair rides, dialysis transport, and hospital discharges. Call 253-374-9087.",
    intro: "Tacoma patients and families trust Noble Medic Wheels for dependable, door-to-door non-emergency ambulance and medical transportation across Pierce County. We serve all Tacoma zip codes with ADA-compliant vehicles and professionally trained drivers who treat every rider with dignity.",
    highlights: ["MultiCare Tacoma General & St. Joseph Medical Center", "Recurring dialysis scheduling", "All Pierce County zip codes", "Wheelchair & ambulatory service"],
    nearbyAreas: ["Lakewood", "Puyallup", "Fife", "University Place"],
  },
  {
    slug: "everett",
    city: "Everett",
    county: "Snohomish County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Medical Transportation in Everett, WA",
    metaDesc: "Noble Medic Wheels serves Everett with ADA-compliant non-emergency ambulance and NEMT — wheelchair rides, dialysis transport, and medical appointment transportation in Snohomish County. Call 253-374-9087.",
    intro: "As Snohomish County's largest city, Everett patients rely on Noble Medic Wheels for professional non-emergency ambulance and medical transportation. From Providence Regional Medical Center to local dialysis centers, we get you there safely and on time, every time.",
    highlights: ["Providence Regional Medical Center", "Snohomish County dialysis centers", "Wheelchair lift-equipped vans", "Same-day & scheduled rides"],
    nearbyAreas: ["Marysville", "Mukilteo", "Mill Creek", "Lynnwood"],
  },
  {
    slug: "renton",
    city: "Renton",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Medical Transportation in Renton, WA | Noble Medic Wheels",
    metaDesc: "Noble Medic Wheels provides non-emergency ambulance, wheelchair, and ambulatory transportation in Renton — dialysis transport, doctor visits, hospital discharges. Serving King County. Call 253-374-9087.",
    intro: "Renton residents have trusted Noble Medic Wheels for reliable, compassionate non-emergency ambulance and medical transportation. From Valley Medical Center to local dialysis clinics, we handle every trip with care and punctuality so you never miss an appointment.",
    highlights: ["Valley Medical Center & nearby clinics", "Recurring dialysis transport", "King County coverage", "ADA-compliant fleet"],
    nearbyAreas: ["Kent", "Tukwila", "Burien", "Newcastle"],
  },
  {
    slug: "lynnwood",
    city: "Lynnwood",
    county: "Snohomish County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Wheelchair Transportation in Lynnwood, WA",
    metaDesc: "Non-emergency ambulance and medical transportation in Lynnwood, WA. ADA-compliant wheelchair rides and dialysis transport serving Snohomish County. Call Noble Medic Wheels at 253-374-9087.",
    intro: "Noble Medic Wheels provides Lynnwood residents with safe, ADA-compliant non-emergency ambulance and medical transportation throughout Snohomish County. Whether heading to Swedish Edmonds, a dialysis center, or a specialist appointment, our drivers are always prompt and professional.",
    highlights: ["Swedish Edmonds & local clinics", "Snohomish County dialysis centers", "Flexible scheduling", "Wheelchair & ambulatory rides"],
    nearbyAreas: ["Edmonds", "Mountlake Terrace", "Bothell", "Everett"],
  },
  {
    slug: "federal-way",
    city: "Federal Way",
    county: "King County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Medical Transportation in Federal Way, WA",
    metaDesc: "Noble Medic Wheels provides ADA-compliant non-emergency ambulance and NEMT in Federal Way — wheelchair transport, dialysis rides, and hospital discharges in King County. Call 253-374-9087.",
    intro: "Federal Way patients and families count on Noble Medic Wheels for dependable, dignified non-emergency ambulance and medical transportation. We serve St. Francis Hospital, dialysis centers, and all medical facilities throughout Federal Way with on-time, door-to-door service.",
    highlights: ["St. Francis Hospital area", "Dialysis & recurring appointments", "All Federal Way zip codes", "Door-to-door assistance"],
    nearbyAreas: ["Auburn", "Kent", "Des Moines", "Tacoma"],
  },
  {
    slug: "marysville",
    city: "Marysville",
    county: "Snohomish County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Medical Transportation in Marysville, WA | Noble Medic Wheels",
    metaDesc: "Noble Medic Wheels offers non-emergency ambulance and NEMT in Marysville — wheelchair rides and dialysis transport serving Snohomish County. Reliable, ADA-compliant service. Call 253-374-9087.",
    intro: "Marysville residents in Snohomish County rely on Noble Medic Wheels for professional non-emergency ambulance and medical transportation. We serve Smokey Point Medical Center, local dialysis clinics, and all medical facilities in and around Marysville with care and reliability.",
    highlights: ["Smokey Point Medical Center", "Snohomish County routes", "Scheduled & recurring rides", "Wheelchair-accessible vehicles"],
    nearbyAreas: ["Everett", "Arlington", "Stanwood", "Lake Stevens"],
  },
  {
    slug: "lakewood",
    city: "Lakewood",
    county: "Pierce County",
    state: "WA",
    metaTitle: "Non-Emergency Ambulance & Wheelchair Transport in Lakewood, WA | Noble Medic Wheels",
    metaDesc: "Noble Medic Wheels provides non-emergency ambulance and medical transportation in Lakewood — ADA-compliant wheelchair rides and dialysis transport in Pierce County. Call 253-374-9087.",
    intro: "Lakewood patients trust Noble Medic Wheels for safe, reliable non-emergency ambulance and medical transportation in Pierce County. From local dialysis centers to specialist appointments and hospital discharges, we provide compassionate, on-time service throughout Lakewood.",
    highlights: ["Pierce County dialysis centers", "Hospital discharge coordination", "ADA-compliant vehicles", "Wheelchair & ambulatory service"],
    nearbyAreas: ["Tacoma", "University Place", "Puyallup", "Spanaway"],
  },
];
